version: '3'

services:
  app:
    build: .
    ports:
      - "9001:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

